x-common-conf: &common
  networks:
    - transcendence
  env_file: "./core/.env"
  restart: on-failure

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/redis
      o: bind

  web_data:
    driver: local
    driver_opts:
      type: none
      device: ./web/
      o: bind

services:
  postgresql:
    container_name: postgresql
    build: ./core/postgresql
    volumes:
      - db_data:/var/lib/postgresql/data
    <<: *common

  redis:
    container_name: redis
    build: ./core/redis
    volumes:
      - redis_data:/data
    <<: *common

  gunicorn-base:
    container_name: gunicorn-base
    build: ./core/gunicorn-base
    image: gunicorn-base
    depends_on:
      - postgresql
    <<: *common

  auth:
    container_name: auth
    build: ./core/auth
    depends_on:
      - gunicorn-base
    volumes:
      - ./core/auth/:/service
    <<: *common

  management:
    container_name: management
    build: ./core/management
    depends_on:
      - auth
    volumes:
      - ./core/management/:/service
      - ./core/auth/user/:/service/user
    <<: *common

  game:
    container_name: game
    build: ./core/game
    depends_on:
      - management
      - redis
    volumes:
      -  ./core/game/:/service
      -  ./core/auth/user/:/service/user
    <<: *common

  nginx:
    container_name: nginx
    build: ./core/nginx     
    depends_on:
      - game
    networks:
      - transcendence

  nginx_frontend:
    container_name: nginx_frontend
    build: ./core/nginx_frontend
    ports:     
      - "80:80"
      - "443:443"  
    volumes:
      - web_data:/var/www/html
    depends_on:
      - nginx
    networks:
      - transcendence
