# Generated by Django 5.1.6 on 2025-02-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', help_text='User avatar', null=True, upload_to='avatars/'),
        ),
    ]
