# Generated by Django 5.1.6 on 2025-03-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
