# Generated by Django 5.1.6 on 2025-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
