# Generated by Django 5.1.6 on 2025-04-22 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0004_friendrequest_rejected_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('rejected_at__isnull', True)), fields=('sender', 'receiver'), name='unique_pending_friend_request'),
        ),
    ]
