# Generated by Django 5.1.6 on 2025-04-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('semifinal', 'Semifinal'), ('final', 'Final')], max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.matchhistory')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tournamenthistory')),
            ],
        ),
    ]
