# Generated by Django 5.1.6 on 2025-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamenthistory',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
