# Generated by Django 5.1.6 on 2025-04-21 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_matchhistory_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tournamenthistory',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
