# Generated by Django 5.1.6 on 2025-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_matchhistory_p1_score_matchhistory_p2_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournamenthistory',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
