x-common-conf: &common
  networks:
    - transcendence
  env_file: ".env"
  restart: on-failure

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pietro/Desktop/ft_transcendence/data/db
      o: bind

  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pietro/Desktop/ft_transcendence/data/redis
      o: bind

  web_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pietro/Desktop/ft_transcendence/web
      o: bind

services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    volumes:
      - db_data:/var/lib/postgresql/data
    <<: *common

  redis:
    container_name: redis
    build: ./redis
    volumes:
      - redis_data:/data
    <<: *common

  gunicorn-base:
    container_name: gunicorn-base
    build: ./gunicorn-base
    image: gunicorn-base
    depends_on:
      - postgresql
    <<: *common

  auth:
    container_name: auth
    build: ./auth
    depends_on:
      - gunicorn-base
      - redis
    volumes:
      - ./auth/:/service
    <<: *common

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - web_data:/var/www/html
    <<: *common
