x-common-conf: &common
  networks:
    - transcendence
  env_file: ".env"
  restart: on-failure

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  web-data:
   driver: local
   driver_opts:
     type: none
     device: /home/pietro/Desktop/ft_transcendence/web  #  THIS NEEDS TO BE STANDARDIZED
     o: bind

  # db_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device:  ${HOME}/data/db
  #     o: bind

services:

  gunicorn-base:
    container_name: gunicorn-base
    build: ./gunicorn-base
    image: gunicorn-base
    # depends_on:
    #   - postgreSQL
    <<: *common

  auth:
    container_name: auth
    build: ./auth
    depends_on:
      - gunicorn-base
    volumes:
      - ./auth/:/service
    expose:    #TODO: REMOVE THIS
      - "8000" #TODO: ^^^^^^^^^^^
    <<: *common

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - web-data:/var/www/html
    <<: *common

  # postgreSQL:
  #   container_name: postgreSQL
  #   build: ./core/postgreSQL
  #   volumes:
  #     - db_data:/var/lib/mysql # TODO: Change this to postgresql data path
  #   <<: *common
