
services:
  postgreSQL:
    container_name: postgreSQL
    build: ./core/postgreSQL
    restart: always
    networks:
      - network-transcendance
    volumes:
      - db_data:/var/lib/mysql # TODO: Change this to postgresql data path


##
# BACKEND GOES HERE
##

  guinicorn-app-base:
    container_name: guinicorn-app-base
    build: ./core/guinicorn-app-base
    depends_on:
      - postgreSQL
    restart: always

  nodejs:
    container_name: nodejs
    build: ./core/nodejs
#   depends_on:
#     BACKEND
    restart: always
    networks:
      -network-transcendence
    volumes: web-data:/data

  nginx:
    container_name: nginx
    build: ./core/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - network-transcendence


networks:
  network-transcendence:
    driver: bridge

volumes:
  web-data:
    driver: local
    driver_opts:
      type: none
      device: # path/goes/here
      o: bind

  db_data:
    driver: local
    driver_opts:
      type: none
      device: # path/goes/here
      o: bind
