# Generated by Django 5.1.6 on 2025-03-03 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.CharField(default='default-avatar.png', max_length=100)),
                ('last_activity', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
