# Generated by Django 5.1.6 on 2025-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
