# Generated by Django 5.1.6 on 2025-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, default="Hello, I'm new here!", max_length=100),
        ),
    ]
