# Generated by Django 5.1.6 on 2025-04-25 19:51

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_otp_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[user.models.validate_username]),
        ),
    ]
