# Generated by Django 5.1.6 on 2025-04-26 22:59

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, default="Hello, I'm new here!", max_length=200, validators=[user.models.validate_motto]),
        ),
    ]
